CREATE TABLE member (
    id int AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO member (name) VALUES ('Adagilsa Duarte Valloto');
INSERT INTO member (name) VALUES ('Adelson Porto Azevedo');
INSERT INTO member (name) VALUES ('Adriana Miguel de Carvalho');
INSERT INTO member (name) VALUES ('Alexandre dos Santos Rodrigues');
INSERT INTO member (name) VALUES ('Alessandra Amaral Emiliano');
INSERT INTO member (name) VALUES ('Almezina Messias dos Santos');
INSERT INTO member (name) VALUES ('Américo Ribeiro da Silva');
INSERT INTO member (name) VALUES ('Ana Lúcia da Silva Campos');
INSERT INTO member (name) VALUES ('Ana Maria da Silva Naves');
INSERT INTO member (name) VALUES ('Ana Paula Baldrete Correia');
INSERT INTO member (name) VALUES ('Ana Paula Lemes Lúcio');
INSERT INTO member (name) VALUES ('Anadir de Oliveira Rodrigues');
INSERT INTO member (name) VALUES ('Arthur Henrique Martins Silva');
INSERT INTO member (name) VALUES ('Camila Núbia Seoane da Silva');
INSERT INTO member (name) VALUES ('Carmelita Silva da Costa');
INSERT INTO member (name) VALUES ('Cibele Alves da Silva');
INSERT INTO member (name) VALUES ('Claudia Cardoso Pereira Ribeiro');
INSERT INTO member (name) VALUES ('Cleber Valloto');
INSERT INTO member (name) VALUES ('Clevson Silva da Costa');
INSERT INTO member (name) VALUES ('Damiana Bezerra de Oliveira');
INSERT INTO member (name) VALUES ('Daniel Lemes Lúcio');
INSERT INTO member (name) VALUES ('Débora Cristina Oliveira');
INSERT INTO member (name) VALUES ('Débora Lemes de Souza');
INSERT INTO member (name) VALUES ('Débora de Lima Santos Emiliano');
INSERT INTO member (name) VALUES ('Denise Rodrigues Martins dos Santos');
INSERT INTO member (name) VALUES ('Edinalva da Silva Guimarães');
INSERT INTO member (name) VALUES ('Edson Ottoboni Coelho');
INSERT INTO member (name) VALUES ('Eliana Lemes da Silva Costa');
INSERT INTO member (name) VALUES ('Eliene Moreira Santos');
INSERT INTO member (name) VALUES ('Eliezer Lemes Flauzino');
INSERT INTO member (name) VALUES ('Elisangela Lemes Garcia da Costa');
INSERT INTO member (name) VALUES ('Elson Rodrigues da Mata');
INSERT INTO member (name) VALUES ('Fábio Santos Porto');
INSERT INTO member (name) VALUES ('Fernando Santos Porto');
INSERT INTO member (name) VALUES ('Gabriel Martins dos Santos');
INSERT INTO member (name) VALUES ('Gabriel Mendes Oliveira');
INSERT INTO member (name) VALUES ('Geanice Ribeiros dos Santos');
INSERT INTO member (name) VALUES ('Geovana Galdino Porto');
INSERT INTO member (name) VALUES ('Geovânio Flausino da Silva');
INSERT INTO member (name) VALUES ('Guilherme Seoane San Nicolas');
INSERT INTO member (name) VALUES ('Iara Cardoso Pereira Neves');
INSERT INTO member (name) VALUES ('Iraci de Oliveira Silva');
INSERT INTO member (name) VALUES ('Iraci Maria Mancio Santos');
INSERT INTO member (name) VALUES ('Ismael dos Santos');
INSERT INTO member (name) VALUES ('Ivonilde Fonseca Ferreira de Oliveira');
INSERT INTO member (name) VALUES ('Jennifer Galdino da Silva');
INSERT INTO member (name) VALUES ('Jéssica Lemes de Souza');
INSERT INTO member (name) VALUES ('Jéssica Menezes da Silva Santos');
INSERT INTO member (name) VALUES ('Jéssica Raiane dos Santos Rosa');
INSERT INTO member (name) VALUES ('João Pedro dos Santos Melo');
INSERT INTO member (name) VALUES ('João Pedro de Sousa Silva');
INSERT INTO member (name) VALUES ('Joice Lemes de Souza');
INSERT INTO member (name) VALUES ('Jonas Lemes Garcia da Costa');
INSERT INTO member (name) VALUES ('Josafá de Sousa Santos');
INSERT INTO member (name) VALUES ('José Francisco Kleber');
INSERT INTO member (name) VALUES ('José Maurício dos Santos');
INSERT INTO member (name) VALUES ('José Ribamar Sebastião Junior');
INSERT INTO member (name) VALUES ('Jutiele da Silva Guimarães Jesus');
INSERT INTO member (name) VALUES ('Kaique Bezerra de Oliveira');
INSERT INTO member (name) VALUES ('Kauê Bezerra de Oliveira');
INSERT INTO member (name) VALUES ('Kelly Ayumi Cardoso da Silva');
INSERT INTO member (name) VALUES ('Larissa Cristina Gomes Serafim');
INSERT INTO member (name) VALUES ('Léa dos Santos Pinto');
INSERT INTO member (name) VALUES ('Leonardo Flausino da Silva');
INSERT INTO member (name) VALUES ('Lívia Rodrigues Oliveira');
INSERT INTO member (name) VALUES ('Lorena Gomes Serafim');
INSERT INTO member (name) VALUES ('Luciana Castro Padoan');
INSERT INTO member (name) VALUES ('Luciana Maria Azevedo');
INSERT INTO member (name) VALUES ('Luzia Helena Lemes da Silva Lúcio');
INSERT INTO member (name) VALUES ('Manoel José da Costa');
INSERT INTO member (name) VALUES ('Márcia Cristina Gomes');
INSERT INTO member (name) VALUES ('Márcia Mônica DAntas de Souza');
INSERT INTO member (name) VALUES ('Márcia Rodrigues');
INSERT INTO member (name) VALUES ('Márcia Rosária dos Santos de Mello');
INSERT INTO member (name) VALUES ('Maria Conceição da Hora da Silva');
INSERT INTO member (name) VALUES ('Maria Eduarda de Souza da Silva');
INSERT INTO member (name) VALUES ('Maria Fernanda Pereira Anselmo');
INSERT INTO member (name) VALUES ('Maria Gorett Oliveira Amaral');
INSERT INTO member (name) VALUES ('Maria Isabel Nunes de Jesus');
INSERT INTO member (name) VALUES ('Maria Lídia Bonfim');
INSERT INTO member (name) VALUES ('Maria do Socorro Paulo Rodrigues');
INSERT INTO member (name) VALUES ('Maria de Souza Gomes');
INSERT INTO member (name) VALUES ('Marilene Alves da Conceição');
INSERT INTO member (name) VALUES ('Marlene Alves da Silva');
INSERT INTO member (name) VALUES ('Mateus Lemes de Souza');
INSERT INTO member (name) VALUES ('Maxsandro Paulo Rodrigues');
INSERT INTO member (name) VALUES ('Meire Ellen Alves da Silva');
INSERT INTO member (name) VALUES ('Mirian Nunes de Jesus Rodrigues');
INSERT INTO member (name) VALUES ('Nelson Azevedo Santiago');
INSERT INTO member (name) VALUES ('Nivaldo Dias Guilherme da Silva');
INSERT INTO member (name) VALUES ('Pedro Garcia da Costa');
INSERT INTO member (name) VALUES ('Pedro Simão Mello');
INSERT INTO member (name) VALUES ('Queila Rute Batista Coelho');
INSERT INTO member (name) VALUES ('Rafael Pereira Ribeiro');
INSERT INTO member (name) VALUES ('Rafael Rodrigues Martins Santos');
INSERT INTO member (name) VALUES ('Raquel Lemes Lúcio');
INSERT INTO member (name) VALUES ('Ricardo Thomazini Santana');
INSERT INTO member (name) VALUES ('Roberta Lima de Jesus');
INSERT INTO member (name) VALUES ('Robson Alves da Silva');
INSERT INTO member (name) VALUES ('Rodrigo Leite da Silva');
INSERT INTO member (name) VALUES ('Samuel Messias Dourado');
INSERT INTO member (name) VALUES ('Sebastiana Maria da Silva Mendes');
INSERT INTO member (name) VALUES ('Silvano de Oliveira');
INSERT INTO member (name) VALUES ('Silvia Regina Santos Emiliano');
INSERT INTO member (name) VALUES ('Stefani Padoan Pena');
INSERT INTO member (name) VALUES ('Tatiane Ferreira de Oliveira');
INSERT INTO member (name) VALUES ('Thainá Padoan Pena');
INSERT INTO member (name) VALUES ('Thaís Emiliano dos Santos');
INSERT INTO member (name) VALUES ('Thaís Ferreira de Oliveira');
INSERT INTO member (name) VALUES ('Thaís Oliveira');
INSERT INTO member (name) VALUES ('Thiago Reis Santos');
INSERT INTO member (name) VALUES ('Vicente Alves da Costa');
INSERT INTO member (name) VALUES ('Vinícius de Souza Martins');
INSERT INTO member (name) VALUES ('Wallace Cordeiro dos Santos');
INSERT INTO member (name) VALUES ('Willian Lemes Garcia da Costa');
INSERT INTO member (name) VALUES ('William Mendes');
INSERT INTO member (name) VALUES ('Zulmira Bandeira Neto');
